FROM vllm/vllm-openai:latest

RUN apt update && apt install -y net-tools

ARG VLLM_UID=1000
ARG VLLM_GID=1000

RUN groupadd -g ${VLLM_GID} app \
  && useradd --create-home --no-log-init -u ${VLLM_UID} -g ${VLLM_GID} vllm

ARG MODEL

COPY --chown=$VLLM_UID:$VLLM_GID ./docker/start_vllm.sh /home/vllm/start_vllm.sh
COPY --chown=$VLLM_UID:$VLLM_GID ./docker/download_model.sh /home/vllm/download_model.sh

ENV MODEL=${MODEL}
ENV NCCL_DEBUG=trace
ENV VLLM_LOGGING_LEVEL=debug
ENV CUDA_LAUNCH_BLOCKING=1
ENV VLLM_TRACE_FUNCTION=0
ENV NCCL_P2P_DISABLE=1
ENV OMP_NUM_THREADS=2
ENV NVIDIA_VISIBLE_DEVICES=all

WORKDIR /home/vllm

USER $VLLM_UID

ENTRYPOINT ["/bin/bash", "/home/vllm/start_vllm.sh"]