FROM vllm/vllm-openai:latest

RUN apt update && apt install -y net-tools

ARG VLLM_UID=1000
ARG VLLM_GID=1000
ARG MODEL

RUN groupadd -g ${VLLM_GID} app \
  && useradd --create-home --no-log-init -u ${VLLM_UID} -g ${VLLM_GID} vllm
RUN mkdir -p /home/vllm/.cache/huggingface/hub/ && chown -R $VLLM_UID:$VLLM_GID /home/vllm/.cache/

COPY --chown=$VLLM_UID:$VLLM_GID ./docker/start_vllm.sh /home/vllm/start_vllm.sh
COPY --chown=$VLLM_UID:$VLLM_GID ./docker/download_model.sh /home/vllm/download_model.sh

WORKDIR /home/vllm

USER $VLLM_UID

ENTRYPOINT ["/bin/bash", "/home/vllm/start_vllm.sh"]