FROM vllm/vllm-openai:latest

ARG RAY_UID=1000
ARG RAY_GID=1000

RUN groupadd -g ${RAY_GID} vllm \
  && useradd --create-home --no-log-init -u ${RAY_UID} -g ${RAY_GID} vllm

RUN mkdir -p /home/vllm/.cache/huggingface/hub/ && \
  chown -R $RAY_UID:$RAY_GID /home/vllm/.cache/

RUN pip install -U ray[serve,dashboard] vllm

USER $RAY_UID
WORKDIR /home/vllm
