services:
  prometheus:
    image: prom/prometheus:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
      - /tmp/ray:/tmp/ray
      - prom-data:/prometheus

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD__FILE: /run/secrets/grafana-admin-password
    volumes:
      - grafana-data:/var/lib/grafana
    secrets:
      - grafana-admin-password

secrets:
  grafana-admin-password:
    environment: GRAFANA_ADMIN_PASSWORD

volumes:
  prom-data:
  grafana-data:
