# prometheus.yaml
global:
  scrape_interval: 5s
  evaluation_interval: 10s

scrape_configs:
  - job_name: vllm
    static_configs:
      - targets:
          - 'host.docker.internal:8080'

  - job_name: 'ray'
    file_sd_configs:
    - files:
      - '/tmp/ray/prom_metrics_service_discovery.json'
